env:
  browser: true
  es2020: true
extends:
  - 'plugin:react/recommended'
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  require-jsdoc: off
  indent: ["error", 4]
  max-len:
    - error
    - code: 100

