export const FETCH_BEGIN = "FETCH_BEGIN";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const FETCH_SONG_LIST_SUCCESS = "FETCH_BOOK_LIST_SUCCESS";
export const FETCH_SONG_SUCCESS = "FETCH_BOOK_SUCCESS";
